"""empty message

Revision ID: 05c3bf6d1389
Revises: 
Create Date: 2022-10-07 23:50:03.436201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05c3bf6d1389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user', 'product')
    )
    op.create_table('products',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('hide_email', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('likes')
    # ### end Alembic commands ###
