"""empty message

Revision ID: 7d37017b200d
Revises: 
Create Date: 2022-10-03 00:31:39.000850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d37017b200d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('products', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
