"""empty message

Revision ID: 79810782afe1
Revises: 
Create Date: 2022-09-19 00:50:09.499839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79810782afe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_table('products')
    # ### end Alembic commands ###
